"""add optimization models

Revision ID: 3d6e3ff90710
Revises: 0df4259bb556
Create Date: 2026-03-23 18:35:28.932829
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d6e3ff90710'
down_revision: Union[str, None] = '0df4259bb556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('method_parameter_defaults',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brew_method_id', sa.Uuid(), nullable=False),
    sa.Column('parameter_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('step', sa.Float(), nullable=True),
    sa.Column('allowed_values', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requires', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brew_method_id'], ['brew_methods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brew_method_id', 'parameter_name', name='uq_method_param_default')
    )
    op.create_index(op.f('ix_method_parameter_defaults_brew_method_id'), 'method_parameter_defaults', ['brew_method_id'], unique=False)
    op.create_table('bean_parameter_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bean_id', sa.Uuid(), nullable=False),
    sa.Column('parameter_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bean_id', 'parameter_name', name='uq_bean_param_override')
    )
    op.create_index(op.f('ix_bean_parameter_overrides_bean_id'), 'bean_parameter_overrides', ['bean_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bean_id', sa.Uuid(), nullable=False),
    sa.Column('brew_setup_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measurement_count', sa.Integer(), nullable=False),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('bounds_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('param_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ),
    sa.ForeignKeyConstraint(['brew_setup_id'], ['brew_setups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bean_id', 'brew_setup_id', name='uq_campaign_bean_setup')
    )
    op.create_index(op.f('ix_campaigns_bean_id'), 'campaigns', ['bean_id'], unique=False)
    op.create_index(op.f('ix_campaigns_brew_setup_id'), 'campaigns', ['brew_setup_id'], unique=False)
    op.create_table('optimization_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_jobs_campaign_id'), 'optimization_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_optimization_jobs_status'), 'optimization_jobs', ['status'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('brew_id', sa.Uuid(), nullable=True),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('predicted_std', sa.Float(), nullable=True),
    sa.Column('parameter_values', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brew_id'], ['brews.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_brew_id'), 'recommendations', ['brew_id'], unique=False)
    op.create_index(op.f('ix_recommendations_campaign_id'), 'recommendations', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_campaign_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_brew_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_optimization_jobs_status'), table_name='optimization_jobs')
    op.drop_index(op.f('ix_optimization_jobs_campaign_id'), table_name='optimization_jobs')
    op.drop_table('optimization_jobs')
    op.drop_index(op.f('ix_campaigns_brew_setup_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_bean_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_bean_parameter_overrides_bean_id'), table_name='bean_parameter_overrides')
    op.drop_table('bean_parameter_overrides')
    op.drop_index(op.f('ix_method_parameter_defaults_brew_method_id'), table_name='method_parameter_defaults')
    op.drop_table('method_parameter_defaults')
    # ### end Alembic commands ###
