"""initial schema

Revision ID: 82cc9e91963b
Revises: 
Create Date: 2026-03-21 16:29:48.472154
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82cc9e91963b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bean_varieties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bean_varieties_name'), 'bean_varieties', ['name'], unique=True)
    op.create_table('brew_methods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brew_methods_name'), 'brew_methods', ['name'], unique=True)
    op.create_table('brewers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temp_control_type', sa.Enum('NONE', 'PRESET', 'PID', 'PROFILING', name='tempcontroltype'), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_step', sa.Float(), nullable=True),
    sa.Column('preinfusion_type', sa.Enum('NONE', 'FIXED', 'TIMED', 'ADJUSTABLE_PRESSURE', 'PROGRAMMABLE', 'MANUAL', name='preinfusiontype'), nullable=False),
    sa.Column('preinfusion_max_time', sa.Float(), nullable=True),
    sa.Column('pressure_control_type', sa.Enum('FIXED', 'OPV_ADJUSTABLE', 'ELECTRONIC', 'MANUAL_PROFILING', 'PROGRAMMABLE', name='pressurecontroltype'), nullable=False),
    sa.Column('pressure_min', sa.Float(), nullable=True),
    sa.Column('pressure_max', sa.Float(), nullable=True),
    sa.Column('flow_control_type', sa.Enum('NONE', 'MANUAL_PADDLE', 'MANUAL_VALVE', 'PROGRAMMABLE', name='flowcontroltype'), nullable=False),
    sa.Column('saturation_flow_rate', sa.Float(), nullable=True),
    sa.Column('has_bloom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brewers_name'), 'brewers', ['name'], unique=True)
    op.create_table('flavor_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flavor_tags_name'), 'flavor_tags', ['name'], unique=True)
    op.create_table('grinders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dial_type', sa.Enum('STEPLESS', 'STEPPED', name='dialtype'), nullable=False),
    sa.Column('display_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ring_sizes_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grinders_name'), 'grinders', ['name'], unique=True)
    op.create_table('origins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_origins_name'), 'origins', ['name'], unique=True)
    op.create_table('papers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_name'), 'papers', ['name'], unique=True)
    op.create_table('people',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=True)
    op.create_table('process_methods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_methods_name'), 'process_methods', ['name'], unique=True)
    op.create_table('roasters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roasters_name'), 'roasters', ['name'], unique=True)
    op.create_table('stop_modes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stop_modes_name'), 'stop_modes', ['name'], unique=True)
    op.create_table('waters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waters_name'), 'waters', ['name'], unique=True)
    op.create_table('beans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roaster_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['roaster_id'], ['roasters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beans_name'), 'beans', ['name'], unique=False)
    op.create_table('brew_setups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brew_method_id', sa.Uuid(), nullable=False),
    sa.Column('grinder_id', sa.Uuid(), nullable=True),
    sa.Column('brewer_id', sa.Uuid(), nullable=True),
    sa.Column('paper_id', sa.Uuid(), nullable=True),
    sa.Column('water_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brew_method_id'], ['brew_methods.id'], ),
    sa.ForeignKeyConstraint(['brewer_id'], ['brewers.id'], ),
    sa.ForeignKeyConstraint(['grinder_id'], ['grinders.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['water_id'], ['waters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brew_setups_name'), 'brew_setups', ['name'], unique=False)
    op.create_table('brewer_methods',
    sa.Column('brewer_id', sa.Uuid(), nullable=False),
    sa.Column('method_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brewer_id'], ['brewers.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['brew_methods.id'], ),
    sa.PrimaryKeyConstraint('brewer_id', 'method_id')
    )
    op.create_table('brewer_stop_modes',
    sa.Column('brewer_id', sa.Uuid(), nullable=False),
    sa.Column('stop_mode_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brewer_id'], ['brewers.id'], ),
    sa.ForeignKeyConstraint(['stop_mode_id'], ['stop_modes.id'], ),
    sa.PrimaryKeyConstraint('brewer_id', 'stop_mode_id')
    )
    op.create_table('water_minerals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('water_id', sa.Uuid(), nullable=False),
    sa.Column('mineral_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ppm', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['water_id'], ['waters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('water_id', 'mineral_name', name='uq_water_mineral')
    )
    op.create_index(op.f('ix_water_minerals_water_id'), 'water_minerals', ['water_id'], unique=False)
    op.create_table('bags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bean_id', sa.Uuid(), nullable=False),
    sa.Column('roast_date', sa.Date(), nullable=True),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_preground', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bean_origins',
    sa.Column('bean_id', sa.Uuid(), nullable=False),
    sa.Column('origin_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['origins.id'], ),
    sa.PrimaryKeyConstraint('bean_id', 'origin_id')
    )
    op.create_table('bean_processes',
    sa.Column('bean_id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process_methods.id'], ),
    sa.PrimaryKeyConstraint('bean_id', 'process_id')
    )
    op.create_table('bean_ratings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bean_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('rated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bean_ratings_bean_id'), 'bean_ratings', ['bean_id'], unique=False)
    op.create_index(op.f('ix_bean_ratings_person_id'), 'bean_ratings', ['person_id'], unique=False)
    op.create_table('bean_variety_link',
    sa.Column('bean_id', sa.Uuid(), nullable=False),
    sa.Column('variety_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['bean_varieties.id'], ),
    sa.PrimaryKeyConstraint('bean_id', 'variety_id')
    )
    op.create_table('bean_tastes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bean_rating_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('acidity', sa.Float(), nullable=True),
    sa.Column('sweetness', sa.Float(), nullable=True),
    sa.Column('body', sa.Float(), nullable=True),
    sa.Column('bitterness', sa.Float(), nullable=True),
    sa.Column('aroma', sa.Float(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bean_rating_id'], ['bean_ratings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bean_tastes_bean_rating_id'), 'bean_tastes', ['bean_rating_id'], unique=True)
    op.create_table('brews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bag_id', sa.Uuid(), nullable=False),
    sa.Column('brew_setup_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('grind_setting', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('dose', sa.Float(), nullable=False),
    sa.Column('yield_amount', sa.Float(), nullable=True),
    sa.Column('pre_infusion_time', sa.Float(), nullable=True),
    sa.Column('total_time', sa.Float(), nullable=True),
    sa.Column('stop_mode_id', sa.Uuid(), nullable=True),
    sa.Column('is_failed', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brewed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bag_id'], ['bags.id'], ),
    sa.ForeignKeyConstraint(['brew_setup_id'], ['brew_setups.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['stop_mode_id'], ['stop_modes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bean_taste_flavor_tags',
    sa.Column('bean_taste_id', sa.Uuid(), nullable=False),
    sa.Column('flavor_tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bean_taste_id'], ['bean_tastes.id'], ),
    sa.ForeignKeyConstraint(['flavor_tag_id'], ['flavor_tags.id'], ),
    sa.PrimaryKeyConstraint('bean_taste_id', 'flavor_tag_id')
    )
    op.create_table('brew_tastes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brew_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('acidity', sa.Float(), nullable=True),
    sa.Column('sweetness', sa.Float(), nullable=True),
    sa.Column('body', sa.Float(), nullable=True),
    sa.Column('bitterness', sa.Float(), nullable=True),
    sa.Column('aroma', sa.Float(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brew_id'], ['brews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brew_id', name='uq_brew_taste_brew_id')
    )
    op.create_index(op.f('ix_brew_tastes_brew_id'), 'brew_tastes', ['brew_id'], unique=False)
    op.create_table('brew_taste_flavor_tags',
    sa.Column('brew_taste_id', sa.Uuid(), nullable=False),
    sa.Column('flavor_tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brew_taste_id'], ['brew_tastes.id'], ),
    sa.ForeignKeyConstraint(['flavor_tag_id'], ['flavor_tags.id'], ),
    sa.PrimaryKeyConstraint('brew_taste_id', 'flavor_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brew_taste_flavor_tags')
    op.drop_index(op.f('ix_brew_tastes_brew_id'), table_name='brew_tastes')
    op.drop_table('brew_tastes')
    op.drop_table('bean_taste_flavor_tags')
    op.drop_table('brews')
    op.drop_index(op.f('ix_bean_tastes_bean_rating_id'), table_name='bean_tastes')
    op.drop_table('bean_tastes')
    op.drop_table('bean_variety_link')
    op.drop_index(op.f('ix_bean_ratings_person_id'), table_name='bean_ratings')
    op.drop_index(op.f('ix_bean_ratings_bean_id'), table_name='bean_ratings')
    op.drop_table('bean_ratings')
    op.drop_table('bean_processes')
    op.drop_table('bean_origins')
    op.drop_table('bags')
    op.drop_index(op.f('ix_water_minerals_water_id'), table_name='water_minerals')
    op.drop_table('water_minerals')
    op.drop_table('brewer_stop_modes')
    op.drop_table('brewer_methods')
    op.drop_index(op.f('ix_brew_setups_name'), table_name='brew_setups')
    op.drop_table('brew_setups')
    op.drop_index(op.f('ix_beans_name'), table_name='beans')
    op.drop_table('beans')
    op.drop_index(op.f('ix_waters_name'), table_name='waters')
    op.drop_table('waters')
    op.drop_index(op.f('ix_stop_modes_name'), table_name='stop_modes')
    op.drop_table('stop_modes')
    op.drop_index(op.f('ix_roasters_name'), table_name='roasters')
    op.drop_table('roasters')
    op.drop_index(op.f('ix_process_methods_name'), table_name='process_methods')
    op.drop_table('process_methods')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_papers_name'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_origins_name'), table_name='origins')
    op.drop_table('origins')
    op.drop_index(op.f('ix_grinders_name'), table_name='grinders')
    op.drop_table('grinders')
    op.drop_index(op.f('ix_flavor_tags_name'), table_name='flavor_tags')
    op.drop_table('flavor_tags')
    op.drop_index(op.f('ix_brewers_name'), table_name='brewers')
    op.drop_table('brewers')
    op.drop_index(op.f('ix_brew_methods_name'), table_name='brew_methods')
    op.drop_table('brew_methods')
    op.drop_index(op.f('ix_bean_varieties_name'), table_name='bean_varieties')
    op.drop_table('bean_varieties')
    # ### end Alembic commands ###
