"""initial schema

Revision ID: 87c4e18a3be4
Revises: 
Create Date: 2026-02-21 23:21:18.856333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c4e18a3be4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('roaster', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bean_id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=True),
    sa.Column('grind_setting', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('preinfusion_pct', sa.Float(), nullable=False),
    sa.Column('dose_in', sa.Float(), nullable=False),
    sa.Column('target_yield', sa.Float(), nullable=False),
    sa.Column('saturation', sa.String(), nullable=False),
    sa.Column('taste', sa.Float(), nullable=False),
    sa.Column('extraction_time', sa.Float(), nullable=True),
    sa.Column('is_failed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('acidity', sa.Float(), nullable=True),
    sa.Column('sweetness', sa.Float(), nullable=True),
    sa.Column('body', sa.Float(), nullable=True),
    sa.Column('bitterness', sa.Float(), nullable=True),
    sa.Column('aroma', sa.Float(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurements_bean_id'), ['bean_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_bean_id'))

    op.drop_table('measurements')
    op.drop_table('beans')
    # ### end Alembic commands ###
