"""add_param_set_fingerprint_rebuild_declined

Revision ID: 9052fc4244a4
Revises: 7313802b80a0
Create Date: 2026-02-26 21:30:35.403623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9052fc4244a4'
down_revision: Union[str, Sequence[str], None] = '7313802b80a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('param_set_fingerprint', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('rebuild_declined', sa.Integer(), nullable=True))

    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.alter_column('temperature',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('flavor_tags',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.alter_column('flavor_tags',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('temperature',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('campaign_states', schema=None) as batch_op:
        batch_op.drop_column('rebuild_declined')
        batch_op.drop_column('param_set_fingerprint')

    # ### end Alembic commands ###
